# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
image: gitpod/workspace-java-17
tasks:
  - name: Script Task
    init: |
      mvn dependency:resolve
      mvn test-compile
      cd gitpod
    command: $MVN_COMMAND

