version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          paths:
            - ~/repo
          keys:
            - demo-java-{{ checksum "pom.xml" }}
            - demo-java-
      - run:
          name: "Setup Maven Dependencies"
          command: |
            mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: demo-java-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/demo-java-0.0.1-SNAPSHOT.jar